main:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Services"
    url: "/#"
    weight: 2

  - name: "Pricing"
    url: "/#"
    weight: 3

  - name: "Resources"
    url: "/#"
    weight: 4

  - name: "Blog"
    url: "/blog"
    weight: 5

  - name: "About"
    url: "/#"
    weight: 6

buttons:
  - name: "Book a call"
    url: "/#"
    weight: 5

footer:
  - name: "Home"
    url: "/#hero"
    weight: 1

  - name: "Services"
    url: "/#"
    weight: 2

  - name: "Pricing"
    url: "/#"
    weight: 3

  - name: "Resources"
    url: "/#"
    weight: 4

  - name: "Blog"
    url: "/#"
    weight: 5

  - name: "About"
    url: "/#"
    weight: 6